# Generated by Django 5.2.2 on 2025-06-07 15:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FitnessClass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Instructor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('available_from', models.TimeField()),
                ('available_to', models.TimeField()),
                ('repeat', models.BooleanField(default=False)),
                ('repeat_days', models.CharField(max_length=100)),
                ('fitness_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bookings.fitnessclass')),
            ],
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_name', models.CharField(max_length=100)),
                ('client_email', models.EmailField(max_length=254)),
                ('class_booked', models.DateTimeField()),
                ('fitness_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bookings.fitnessclass')),
                ('instructor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bookings.instructor')),
            ],
        ),
    ]
