# Generated by Django 5.2.2 on 2025-06-09 08:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='booking',
            old_name='class_booked',
            new_name='class_booking_at',
        ),
    ]
