# Generated by Django 5.2.2 on 2025-06-09 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0002_rename_class_booked_booking_class_booking_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='fitnessclass',
            name='max_capacity',
            field=models.IntegerField(default=10, help_text='Maximum number of participants allowed'),
        ),
    ]
