# Generated by Django 5.2.2 on 2025-06-09 12:53

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bookings", "0003_fitnessclass_max_capacity"),
    ]

    operations = [
        migrations.AlterField(
            model_name="booking",
            name="class_booking_at",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name="instructor",
            name="repeat_days",
            field=models.JSONField(default=list),
        ),
    ]
