# Generated by Django 5.2.2 on 2025-06-09 12:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("bookings", "0004_alter_booking_class_booking_at_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="instructor",
            name="repeat",
        ),
    ]
